services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: clinic-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-clinic_db}
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - clinic-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Mongo Express - MongoDB Web Interface
  mongo-express:
    image: mongo-express:1.0.0
    container_name: clinic-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-changeme}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-changeme}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD:-changeme}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - clinic-network

  # Backend API - FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: clinic-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-changeme}@mongodb:27017/
      - DATABASE_NAME=${MONGO_INITDB_DATABASE:-clinic_db}
      - SECRET_KEY=${BACKEND_SECRET_KEY:-your-secret-key-here}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-jwt-secret-key-here-change-in-production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - ENVIRONMENT=development
      - DEBUG=True
    volumes:
      - ./backend:/app
      - backend_venv:/app/venv
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - clinic-network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend - React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: clinic-frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - API_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - clinic-network
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongodb_data:
    name: clinic-mongodb-data
  backend_venv:
    name: clinic-backend-venv
  frontend_node_modules:
    name: clinic-frontend-node-modules

networks:
  clinic-network:
    name: clinic-network
    driver: bridge